"""empty message

Revision ID: 35db78d2303e
Revises: d49905e2b775
Create Date: 2024-08-13 12:20:01.224387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35db78d2303e'
down_revision: Union[str, None] = 'd49905e2b775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_movie_user', table_name='comments')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    op.add_column('ratings', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'date_created')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_index('ix_comments_movie_user', 'comments', ['movie_id', 'user_id'], unique=False)
    # ### end Alembic commands ###
