"""empty message

Revision ID: 71cc78eb07a5
Revises: 35db78d2303e
Create Date: 2024-08-13 12:55:17.384070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cc78eb07a5'
down_revision: Union[str, None] = '35db78d2303e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_cuid', table_name='comments')
    op.drop_column('comments', 'cuid')
    op.drop_index('ix_ratings_ruid', table_name='ratings')
    op.drop_column('ratings', 'ruid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('ruid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index('ix_ratings_ruid', 'ratings', ['ruid'], unique=True)
    op.add_column('comments', sa.Column('cuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index('ix_comments_cuid', 'comments', ['cuid'], unique=True)
    # ### end Alembic commands ###
